### ISSUE TITLE
You may need to make your repo public

### ISSUE THREAD

**Issue by ghost** [na4ma4/traefik-acme#1]
I get the below error when trying to pull from na4ma4/traefik-acme via docker-compose.

Error response from daemon: pull access denied for na4ma4/traefik-acme, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by ghost** [comment]
I've just issued the docker login command, and I can confirm it isn't working.

**Comment by na4ma4** [comment]
that's my mistake, it's `ghcr.io/na4ma4/traefik-acme` not `na4ma4/traefik-acme`, I'll update the readme.
