### ISSUE TITLE
Docker parameter for cert resolver

### ISSUE THREAD

**Issue by klangborste** [na4ma4/traefik-acme#3]
Hello,

is there a possibility to set a option for the cert resolver?
I get an:
`ERRO[0000] certificate resolver not found
`

**Comment by na4ma4** [comment]
There is a parameter for `--certificate-resolver <resolver>` if it's not the default ?

**Comment by klangborste** [comment]
Switched to another Docker container for DDNS and unfortunately had no further research here, can't say anything more about it

**Comment by na4ma4** [comment]
All good, I'll close the ticket off.
