### ISSUE TITLE
certificate resolver not found

### ISSUE THREAD

**Issue by etouraille** [na4ma4/traefik-acme#60]
Hello, 

I use the docker container to generate my certs : 

`docker run --rm  -v "/home/ubuntu/docker/traefik:/input"  -v "/docker/myservice/certs:/output"   --workdir /output ghcr.io/na4ma4/traefik-acme:latest --acme /input/cert.json --certificate-resolver tls-challenge   --debug subdomain.domain.fr `

I Use traefik v24, here is my toml.

`[api]
    dashboard = true
    insecure = true

[entryPoints]
    [entryPoints.web]
    address = ":80"
    [entryPoints.web.http]
        [entryPoints.web.http.redirections]
            [entryPoints.web.http.redirections.entryPoint]
                to = "websecure"
                scheme = "https"
                permanent = true

[entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.http.tls]
        certResolver = "default"

[providers]
    [providers.docker]
        watch = true
        exposedByDefault = false
        network = "web"

[certificatesResolvers]
    [certificatesResolvers.default]
        [certificatesResolvers.default.acme]
            email = "edouard.touraille@gmail.com"
            storage = "acme.json"
            caServer = "https://acme-v01.api.letsencrypt.org/directory"
        [certificatesResolvers.default.acme.tlsChallenge]`

Could you help me with this error ? 

Thanks in advance.

**Comment by na4ma4** [comment]
I think you need to change `--acme cert.json` to `--acme acme.json`.

And to confirm that the path to the acme.json is `/home/ubuntu/docker/traefik/acme.json` on the host system ?

**Comment by etouraille** [comment]
I solved this using default, thanks for the awnser.
